
services:
  app:
    container_name: holdingshub-app-prod
    image: holdingshub:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_APP_ORIGIN: ${PUBLIC_URL}
    env_file:
      - .env.docker
    environment:
      - NEXT_PUBLIC_APP_ORIGIN=${PUBLIC_URL}  # runtime, but note: NEXT_PUBLIC_* is baked at build for client bundle
      - PORT=3000
    restart: unless-stopped
    networks:
      - web
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s

  caddy:
    container_name: holdingshub-caddy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN}
    depends_on:
      - app
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: bridge
